---
- name: create domain
  win_domain:
    dns_domain_name: "{{ domain_dns_name }}"
    domain_netbios_name: "{{ domain_netbios_name }}"
    safe_mode_password: "{{ domain_safe_mode_password }}"
  register: domain_install

- name: reboot server
  win_reboot:
   msg: 'Installing AD. Rebooting...'
   pre_reboot_delay: 15
  when: domain_install.changed

- name: Set internal DNS server 
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - '127.0.0.1'

- name: Wait for DNS available
  win_wait_for:
    port: 53
    delay: 10
    sleep: 5
    timeout: 600

- name: Test - add domain user
  win_domain_user:
    name: testuser
    password: Passw0rd
    state: present
  register: win_domain_user
  until: win_domain_user.failed == false
  retries: 40
  delay: 15
  ignore_errors: yes
  changed_when: False

- name: Test - remove domain user
  win_domain_user:
    name: testuser
    state: absent
  changed_when: False