---
- name: Create new Windows domain in a new forest with specific parameters
  ansible.windows.win_domain:
    # create_dns_delegation: "{{ dc_create_dns_delegation }}"
    # database_path: "{{ dc_database_path }}"
    dns_domain_name: "{{ dc_domain_dns_name }}"   
    domain_netbios_name: "{{ dc_domain_netbios_name }}"  
    safe_mode_password: "{{ dc_safe_mode_password }}"
    # sysvol_path: "{{ dc_sysvol_path }}"
    # domain_mode: Win2012R2
    # forest_mode: Win2012R2
  register: domain_install

- name: reboot server
  win_reboot:
   msg: 'Installing AD. Rebooting...'
   pre_reboot_delay: 15
  when: domain_install.changed

- name: Set internal DNS server 
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - '127.0.0.1'

# Source: https://madlabber.wordpress.com/2019/09/08/creating-a-new-active-directory-forest-with-ansible/